# Generated by Django 4.2.7 on 2025-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_app', '0003_chapterschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
